### PR TITLE
[WIP] Added custom promise pages

### PR DESCRIPTION
**Pull request by MrLuit**
### Description of your *pull request*, and other information

This PR adds a custom page for every promise 🎉 

### Make sure you are using the *latest* version: pull latest commits before reporting any issues.
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.

### Before submitting a *Pull Request* make sure you have:
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) and [CONTRIBUTING.md](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/CONTRIBUTING.md) pages.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/pulls?utf8=%E2%9C%93&q=) through previous Pull Requests for similar issues including closed ones or just looking at the promises template

---

### CODE REVIEW

**Comment by VirenMohindra** [comment]
Great work as always, this is functioning really well, and all round is a fantastic, if not essential addition to the development of this site. I've listed a few changes we could add on to this PR to make it function better - 

1. Sharing through Facebook shows an incorrect preview box, should use jekyll to pipe in the correct relative link.

Example:
screen shot 2017-05-03 at 1 36 34 pm

I don't think this needs to apply to Twitter, directing users to the main landing page is good enough.

**Open for discussion --**

1. Maybe the whole promise section can be clickable instead of just the `chevron` on the right? I'm open to discussion. This might make it more clear. If it messes with filtering we can leave it as it is right now.



[W3 standard errors:](https://validator.w3.org)
1. `<style>` is in the body. 
```
div></nav><style> hr { 
```
2. The element `button` must not appear as a descendant of the `a` element.
 
```
<button class="btn facebook">
```
3. Duplicate ID `src`.
```
/a><li><a id='src' target='_blank' href='https://youtu.be/4t1xR9U6IAU?t=44s'>
```
4. The first occurrence of ID src was here.
```
/a><li><a id='src' target='_blank' href='https://web.archive.org/web/20161109222320/http://www.npr.org/2016/11/09/501451368/here-is-what-donald-trump-wants-to-do-in-his-first-100-days'>https://w
```
5. The first occurrence of ID src was here.
```
s'><li><a id='src' target='_blank' href='https://web.archive.org/web/20161101093508/https://www.donaldjtrump.com/press-releases/donald-j.-trump-delivers-groundbreaking-contract-for-the-american-vote1'>https://w
```



Fantastic work.

**Comment by MrLuit** [comment]
Correct me if I'm wrong, but I think the facebook url works fine. The problem is that the pages are not online yet, so facebook doesn't recognize the URL.

I like your suggestion of making the whole promise clickable but I'm afraid it won't look good.

I will try to fix the W3 errors. Thanks for pointing out.

**Comment by MrLuit** [comment]
I fixed all the W3 issues and I created a seperate comments.js file and promisepage.css. I noticed the other CSS was in .sass but I don't know how that works so maybe you want to convert the css to sass.

Another thing: Maybe I should implement #145 before merging. This is because we should not change url's after implementing the custom url's thing.

Edit: Implemented the mechanics of #145 but didn't actually make a description for anything.

**Comment by VirenMohindra** [comment]
## Mobile responsiveness

1. Reddit comments aren't responsive - as far as I know this is only applicable to comments in links. How can we combat this?

screen shot 2017-05-03 at 5 16 28 pm

2. Sources take time conforming into the viewport

screen shot 2017-05-03 at 5 16 15 pm

**Comment by VirenMohindra** [comment]
htmlproofer failed:

```
 ./_site/institute-a-hiring-freeze-on-all-federal-employees-to-reduce-federal-workforce-through-attrition-exem/index.html
  *  internal script ../js/comments.js does not exist (line 1)
```

**Comment by MrLuit** [comment]
Fixed the HTML Proofer issue, fixed the line-wrap in panel, improved markdown to use reddit markdown.

Problem 2 is interesting. If we want to display sources (on mobile) it would look good to use the <title> of the source instead of the URL. I used to do this with Javascript (thats why it took some time to render the correct title) and I have also tried doing it with Ruby.

Doing it with Ruby is possible but the `rake serve` will take really long. I have not removed the code from Rakefile but the code is inactive.

Edit: I have no idea why the Travis CI build failed.

**Comment by MrLuit** [comment]
Update: Travis CI build works again and removed the "https://web.archive.org/web/" from the `<a>` (only what the user sees, not the actual `href`)

The only thing left to do is to create accurate titles and descriptions before merging.

**Comment by VirenMohindra** [comment]
I'm happy with this PR and I'm fine with merging to the master branch. I'll go over it once more but any more thoughts?

**Comment by VirenMohindra** [comment]
I was thinking of adding the font awesome icons next to the status for more accessibility. Thoughts?

**Pull request merged**
