### PR TITLE
CSS Fix

### PR DESCRIPTION
**Pull request by alexanderankin**
I saw that the css wasnt working, and that you guys had a lot of assets being inlined with html, so i decided i would make some bundles for you.

### CODE REVIEW

**Comment by alexanderankin** [comment]
font and mozilla firefox layout fix

**Comment by VirenMohindra** [comment]
when running `./bower_commands.sh` moving fonts fail

**Comment by VirenMohindra** [comment]
If you are also planning to fix css issues, please look at #23

I just saw what you were talking about in terms of the Mozilla firefox fix:

screen shot 2016-11-16 at 8 26 21 am

If you'd like to submit a separate PR for that only and keep this pull request open, I'm totally down for that.

**Comment by alexanderankin** [comment]
I cannot reproduce? :face_with_head_bandage: :face_with_head_bandage: 

its not even like a tricky script, is the thing...

**Comment by VirenMohindra** [comment]
Tried running the bash script on a fresh install straight from your forked master, this was the output.


```
172-16-38-193:trumptracker.github.io-master USER$ ./bower_commands.sh
Installing Bower Components
bower cached        https://github.com/twbs/bootstrap.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#3.3.7
bower cached        https://github.com/jquery/jquery-dist.git#3.1.1
bower validate      3.1.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower install       bootstrap#3.3.7
bower install       jquery#3.1.1

bootstrap#3.3.7 bower_components/bootstrap
└── jquery#3.1.1

jquery#3.1.1 bower_components/jquery


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 1.7.9 → 1.8.0    │
   │   Run npm i -g bower to update      │
   │                                     │
   ╰─────────────────────────────────────╯


Assembling CSS and JS Assets
  In directory: /Users/virenmohindra/Desktop/trumptracker.github.io-master
    Script Location: /Users/virenmohindra/Desktop/trumptracker.github.io-master
    Script Name: ./bower_commands.sh


  Concatenating CSS:
    Files (in order): ('<!-- Latest compiled and minified CSS -->')
      Bootstrap Minified CSS
      Custom Stylesheet
tr: Illegal byte sequence
    Making /tmp/styles.css

    Successfully made ./assets/css.css.

  Concatenating JS:
    Order Summary:

      <!-- Font Awesome -->
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <!-- Latest compiled and minified JavaScript --> (bootstrap)
    File Sources:

    Successfully made ./assets/js.js.

Done Assembling Assets
Moving fonts
  cp ./bower_components/bootstrap/dist/fonts ./fonts -r
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
moving fonts failed
done

172-16-38-193:trumptracker.github.io-master virenmohindra$ gem install jekyll bundler
Successfully installed jekyll-3.3.1
Parsing documentation for jekyll-3.3.1
Done installing documentation for jekyll after 1 seconds
Successfully installed bundler-1.13.6
Parsing documentation for bundler-1.13.6
Done installing documentation for bundler after 3 seconds
2 gems installed
```

1. tr: Illegal byte sequence
2. moving fonts failed

I'm guessing there was a syntax error with `cp`

**Pull request closed without merging**
