### PR TITLE
Adding tweet button

### PR DESCRIPTION
**Pull request by MrLuit**
Add tweet button and shorten Reddit url's.

Ofcourse messages can be changed but I think this is a good start to #33 

[Click here to go to the example page](https://mrluit.github.io/trumptracker.github.io/)

### CODE REVIEW

**Comment by VirenMohindra** [comment]
We'll need to pull the policy in the tweet (or atleast part of it) to know what people are talking about, since none of the policies have permalinks.

**Comment by MrLuit** [comment]
@VirenMohindra I have thought about this but I just thought it was easier to use the reddit link because it is very hard to put the policy in less than 123 characters.

**Comment by VirenMohindra** [comment]
I don't think I made the right decision with moving comments off-site.

Your work is still commendable -- because people still needed to comment on Reddit and your bot helped automate a whole lot of manual labor.

With Disqus integration on the site, we can create permalinks for each policy and then link that while tweeting to Trump.

**Comment by MrLuit** [comment]
This pull request is really outdated, so I'm going to close it. Will probably implement when the permalinks with Disqus are figured out

**Pull request closed without merging**
