### PR TITLE
Convert to Jekyll and generate dynamically from JSON

### LINKED ISSUE #11: Make it dynamic
This is great but like you said, would benefit from not having everything hard-coded. I'd suggest a simple static site generator like Jekyll with the "promises" being pulled from a JSON list.

I'm happy to submit a PR if you're interested in taking that route.

### PR DESCRIPTION
**Pull request by alanfriedman**
This PR will replace the existing site with a Jekyll generated dynamic site, based off the `_data.data.json` file (I just tweaked @jayrav13's file a bit).

To run locally, follow the instructions in this branch's readme.

There are a few small merge conflicts that need to be resolved manually but looks like it shouldn't be too hard.

Also please double-check that I got everything.

Closes #11

### CODE REVIEW

**Comment by VirenMohindra** [comment]
You're doing god's work. What an insanely fast turn-around time.

Off the bat, the tabs are a bit jumbled up, maybe because the json was parsed incorrectly? 

Few additions I made which will need to be implemented in the new Jekyll generated site - 
- Days till Inauguration: 69
- Correct Tuesday, November **8th**, 2016, to Tuesday, November **9th** 2016 in the description.
- The table structure seems to have been removed - it looks more like a list now.
- From the First 100 Days, my small gist got left out, why didn't the JSON parse this? (probably because they were sprinkled with `b` tags). Context is given below in quotations:

> On November 8th, Americans will be voting for this 100-day plan to restore prosperity to our economy, security to our communities, and honesty to our government. This is my pledge to you. And if we follow these steps, we will once more have a government of, by and for the people.
> 
> Trump Tracker will be following each and every policy to see they get fulfilled
- Is the highlighting still working? For instance, can we still highlight each single issue with a `<tr class="success">` or `<tr class="danger">` tag when he doesn't complete a policy or promise?  Negotiate the release of all U.S. prisoners held in Iran before taking office. (Five hostages were recently released, including Washington Post reporter Jason Rezaian; Trump has taken some credit for this.) - **Very important come inauguration time.**

Other than these small nuances, you've done some exemplary work. I can add you as a collaborator if you'd like.

**Comment by alanfriedman** [comment]
Thanks, I'd be happy to be a collaborator.

Tab order is based on the order of the tabs array in JSON.

I didn't see a need for tables (there weren't any columns) but feel free to add it back. If it's just for the color classes we can implement that on list items.

**Comment by VirenMohindra** [comment]
Added!
If you are pushing this to the main repo, please add back the tables, because bootstrap adds this padding which makes it much cleaner. 

The lines are important to distinguish between each policy. If we don't have separate sections there's no point in having highlights so please remember to add that in.

**Comment by alanfriedman** [comment]
@VirenMohindra Because of the size of this PR I'm recommending we merge it in and apply the new fixes after. The longer this branch sits out the harder it gets.

**Comment by VirenMohindra** [comment]
I would still prefer to keep tables throughout the site.

Can we merge it as soon as we've implemented the site to what it looks like right now (including the search functionality and comment section (integrated through reddit)?

I'll switch off all new commits and pull requests until we've figured out how to seamlessly migrate to Jekyll.

**Comment by alanfriedman** [comment]
Yeah let's prevent further commits to master until this is merged in. I'll do my best to get this updated with the upstream master. Still not sure I understand tables but I'll do what I can. Are you planning to add columns later?

**Comment by alanfriedman** [comment]
@VirenMohindra Just pushed updates. Let me know how it looks.

I left out the reddit link because we'll need to work that into the data.json schema.

Conflicts have been resolved...

**Comment by VirenMohindra** [comment]
all round fantastic work. how would you like to approach comments? Since we don't have permalinks to all of the Reddit links yet.

**Comment by VirenMohindra** [comment]
this html5 validation error is possible because of the comments. We can fix it in due time.

`A table row was 3 columns wide and exceeded the column count established by the first row`

**Pull request merged**
