### PR TITLE
Update data.yaml

### PR DESCRIPTION
**Pull request by iProdigy**
### Description of your *pull request*, and other information
Update data.yaml
* Budget updates
* Intervention in Syria
* Remove duplicated promises
* Begin removing immeasurable promises

---
- [x] I've **verified** and **I assure** that I'm looking at the latest version of Trump Tracker.
- [x] At least skimmed through [README](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/README.md) and **most notably** the [To Do List](https://github.com/TrumpTracker/trumptracker.github.io#to-do-list) and [CONTRIBUTING.md](https://github.com/TrumpTracker/trumptracker.github.io/blob/master/CONTRIBUTING.md) pages.
- [x] [Searched](https://github.com/TrumpTracker/trumptracker.github.io/pulls?utf8=%E2%9C%93&q=) through previous Pull Requests for similar issues including closed ones or just looking at the promises template

### CODE REVIEW

**Comment by MrLuit** [comment]
First should be compromised.

**Comment by iProdigy** [comment]
Fixed @MrLuit, thank you for pointing that out

**Review by VirenMohindra — COMMENTED** [review]
Everything looks good, fantastic reporting as usual. We might need more information regarding 'Provide more funding for police training.'

Could you provide a specific line in the budget which specifies decrease? I'm guessing the Administration didn't want to shed light on this broken promise so they're not adding anything related to it in the budget.

Thoughts?

**Comment by VirenMohindra** [comment]
Maybe this?

https://web.archive.org/web/20170328171156/https://www.washingtonpost.com/news/post-nation/wp/2017/03/16/nypd-says-trumps-budget-would-gut-new-yorks-counterterrorism-efforts-make-the-city-less-safe/


Refers to the federal budget as a whole though.

**Comment by iProdigy** [comment]
I marked that promise as broken due to no mention of increasing general police training in this budget blueprint while cutting the Department of Justice by $1.1B. Furthermore, if Trump were to cut all federal funding to sanctuary cities (as he has promised), police departments would suffer.

**Pull request merged**
