### PR TITLE
Minor table formatting updates, change tabs to pills style, add icons…

### PR DESCRIPTION
**Pull request by monkeyp1ckles**
… to table headings, convert comment link to button style and add icon.

### CODE REVIEW

**Comment by VirenMohindra** [comment]
Adds a broken file icon to headings inside each Policy. 

screen shot 2016-11-20 at 6 07 06 pm

**Comment by monkeyp1ckles** [comment]
@VirenMohindra Let me know what icon you'd like and I'll make the change.

**Comment by VirenMohindra** [comment]
I'd prefer no icon but if it cannot be empty then please choose an appropriate one from http://fontawesome.io/ and push to the branch again.

I'd prefer it to be empty though.

**Comment by VirenMohindra** [comment]
branch had conflicts

Explanation for why I didn't add all of the changes:

1. `<th colspan="3">` throws errors during html5 validation
2. Since I didn't add the colspan, I didn't need to add strong tags etc which succeded it.

**Comment by VirenMohindra** [comment]
Please thoroughly test before adding formatting changes - search broke because of the tab pills.
Referencing #59.

**Pull request closed without merging**
