### PR TITLE
Fixed search bugs - Case sensitive and form submit

### PR DESCRIPTION
**Pull request by MattSandy**
Let me know if I did this branching thing right.

### CODE REVIEW

**Comment by VirenMohindra** [comment]
Hey, we just migrated to Jekyll, would you mind fixing the conflicting issues so I can immediately merge them?

And yes, the branch is functioning correctly.

**Comment by MattSandy** [comment]
Alright, I think I did it. Couldn't install Jekyll to test though (gcc issue I need to upgrade xcode for).

**Comment by VirenMohindra** [comment]
Still a few conflicts that must be resolved. I'll check them out, because I can't seem to automatically merge right now.

Are you sure you are synced up to the latest commit?

**Comment by alanfriedman** [comment]
@MattSandy I can help getting Jekyll setup, just let me know.

**Comment by MattSandy** [comment]
Git is still a little confusing for me, but updated xcode and everything seems to work. I think I am up to date and have the hang of it. Sorry for causing conflicts.

**Comment by VirenMohindra** [comment]
Please feel free to reopen this issue whenever it is ready, thank you for your contribution.

**Pull request closed without merging**
