### PR TITLE
Adding Reddit comments to data.json

### PR DESCRIPTION
**Pull request by MrLuit**
Adding comment links to reddit :)

### CODE REVIEW

**Comment by MrLuit** [comment]
Done

**Comment by VirenMohindra** [comment]
we had moved to `yaml` so 498108ca032548a536cc5ea45ded3751633f376c fixes this

**Comment by VirenMohindra** [comment]
How are we managing new policy additions? Is your bot running continuously and watching for new policy additions to `_data.yaml` or will we have to manually add it in?

thank you for your work.

**Comment by MrLuit** [comment]
I have not yet set up a cronjob, but until I have you can always tag @MrLuit on github or /u/Luit03 on reddit. Yaml is harder than json so before I set up a cronjob I need to update that.

Thanks for helping you out on this great project. I will certainly help with some other features when I have some spare time.

**Pull request closed without merging**
