### PR TITLE
Added search functionality to tab panes

### PR DESCRIPTION
**Pull request by MattSandy**
The search is case insensitive and retains the heading for the section. More functionality could probably be added, but it works and is responsive (on key up).

### CODE REVIEW

**Comment by VirenMohindra** [comment]
Great work. Crossing this off the to do list. Can you implement a site wide search functionality in the `nav-bar` or just above the `tab-headings` and I'll merge the request as soon as possible.

Also The language attribute on the `script` element is obsolete. You can safely omit it.
Reference: [w3 HTML5 Validator](https://validator.w3.org)

**Comment by MattSandy** [comment]
Sure thing, give me a couple minutes.

**Comment by MattSandy** [comment]
First collaborative git project for me (used SVN before), so let me know if I need to do anything else with pull requests or whatnot. The global search code has been committed.

**Comment by VirenMohindra** [comment]
Just reviewed everything, seamlessly integrated into the site. All round fantastic work.

One thing - could you make a branch next time? It'll be easier for me to review and push onto the master next time.

**Comment by MattSandy** [comment]
I will look into that. I have only used git for personal projects up until now.

**Comment by VirenMohindra** [comment]
1. When you press enter it refreshes and redirects to https://trumptracker.github.io/?search=QUERY_HERE, might need to disable enter because you've already implemented instant search results and it is slightly counter intuitive?

While on mobile - 
1. Will need to display the main search on mobile too, like you've done for the sub-headings.

**Comment by VirenMohindra** [comment]
1. Implemented a comment section - will need to add it in search functionality.

Also found a bug - Capitalizing a word while searching produces no results.

For example:

the keyword `Repeal` won't show anything, while `repeal` will.

**Pull request merged**
